image: "python:3.6-buster"

before_script:
    - pip install .
    
pylint_lib:
    script:
        - pylint ./dell_storage_api

pylint_bin:
    script:
    - pylint ./bin/dell-storage-client

mypy_lib:
    script:
    - mypy ./dell_storage_api

mypy_bin:
    script:
    - mypy ./bin/dell-storage-client
